const data = {
    products : [
        {
            _id: '1',
            name : 'Nike Slim Shirt',
            category : 'Shirts',
            image : '/images/p1.jpg',
            price : 120,
            countInStock : 10,
            brand : 'Nike',
            rating: 4.5,
            numReviews : 10,
            description : 'high quality product',
        },
        {
            _id: '2',
            name : 'Lacoste Slim Shirt',
            category : 'Pants',
            image : '/images/p2.jpg',
            price : 120,
            countInStock : 20,
            brand : 'Nike',
            rating: 4.5,
            numReviews : 10,
            description : 'high quality product',
        },
        {
            _id: '3',
            name : 'Nike Slim Shirt',
            category : 'Shirts',
            image : '/images/p3.jpg',
            price : 120,
            countInStock : 0,
            brand : 'Nike',
            rating: 4.5,
            numReviews : 14,
            description : 'high quality product',
        },
        {
            _id: '4',
            name : 'Adidas Slim Shirt',
            category : 'Shirts',
            image : '/images/p4.jpg',
            price : 100,
            countInStock : 12,
            brand : 'Adidas',
            rating: 4.5,
            numReviews : 10,
            description : 'high quality product',
        },
    ]
}
export default data;